/*******************************************************************************
 * Copyright (C) 2011-2017 Khaled Yakdan.
 * All rights reserved.
 ******************************************************************************/
#pragma once

enum ExpressionType{
	//ASSICIATIVE_COMMUTATIVE_EXPRESSION,
	MULTIPLICATION_EXPRESSION,
	ADDITION_EXPRESSION,
	AND_EXPRESSION,
	OR_EXPRESSION,
	XOR_EXPRESSION,
	
	//BINARY_NON_COMMUTATIVE_EXPRESSION,
	EXPONENTIATION_EXPRESSION,
	REMAINDER_EXPRESSION,
	DIVISION_EXPRESSION,
	SHIFT_EXPRESSION,
	
	GLOBAL_VARIABLE,
	//NUMERIC_LITERAL,
	REGISTER,
	STACK_VARIABLE,
	STRING_LITERAL,
	TERNARY_EXPRESSION,
    
	//UNARY_EXPRESSION,
	NEGATION_EXPRESSION,
	LOGICAL_NOT_EXPRESSION,
	ADDRESS_EXPRESSION,

	//Constant
	NUMERIC_CONSTANT,
	SYMBOLIC_CONSTANT,

    POINTER,
    FLAG,
    LOCAL_VARIABLE,
    CONDITION,
    LOWLEVEL_CONDITION,
    HIGHLEVEL_CONDITION,
	BIT_CONCATENATION,
	MATH_FUNCTION,
	FUNCTION
};
